In [1]:
import pandas as pd

In [ ]:


df = pd.read_csv("e33335be-f99c-4a76-9af8-708bc1bb5e57_Series - Metadata.csv")

df.head()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,AFG,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,1.0093,0.9402,0.9388,1.0172,0.9024,1.2763,...,7.6117,10.3972,11.8099,12.1046,12.1436,12.4864,11.298,11.6486,12.0684,..
1,Afghanistan,AFG,Control of Corruption - Governance estimate (a...,GOV_WGI_CC.EST,-1.63745039999999,..,-1.5434271,-1.5453868,-1.50732,-1.57150029999999,...,-1.56501159999999,-1.54351939999999,-1.5398439,-1.5013636,-1.40089,-1.22202489999999,-1.1719937,-1.1987543,-1.3087183,..
2,Afghanistan,AFG,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,-2.8505004,..,-2.43357069999999,-2.387388,-2.1912579,-2.133959,...,-2.4834928,-2.61393089999999,-2.5824048,-2.5893714,-2.5896897,-2.4506389,-2.4492487,-2.3922828,-2.2052112,..
3,Afghanistan,AFG,Population ages 65 and above (% of total popul...,SP.POP.65UP.TO.ZS,2.26197021041933,2.26194811585133,2.26397395055888,2.26675269120301,2.2686467503968,2.26974934650551,...,2.35549736125691,2.35973702156897,2.36712047688815,2.37615338349114,2.37073382439812,2.35254951873996,2.35514236704931,2.37753752819851,2.400970026561,2.42557886023075
4,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,64.767279818427,64.5975727246894,64.4168880125936,64.1762314183241,63.8266086780653,63.3190255280017,...,72.7659101386992,65.8623470043896,67.2271774798558,58.3308722306744,46.0870936659706,..,..,..,..,..

In [13]:
df.describe()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
count,6720,6720,6720,6720,6720,6720,6720,6720,6720,6720,...,6720,6720,6720,6720,6720,6720,6720,6720,6720,6720
unique,210,210,32,32,4675,3732,4837,4819,4924,5134,...,5342,5350,5361,5356,5318,5002,4426,3854,3358,1044
top,Afghanistan,AFG,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
freq,32,32,210,210,1707,2615,1466,1477,1408,1194,...,872,874,862,865,901,1319,1968,2587,3322,5662

In [14]:
import pandas as pd

# Identify columns containing years
year_cols = [col for col in df.columns if "[YR" in col]

# Convert year columns to numeric values
df[year_cols] = df[year_cols].replace("..", pd.NA)

df[year_cols] = df[year_cols].apply(
    pd.to_numeric, errors="coerce"
)

In [20]:
df.head()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,AFG,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,1.00930,0.940200,0.938800,1.017200,0.902400,1.276300,...,7.611700,10.397200,11.809900,12.104600,12.143600,12.486400,11.298000,11.648600,12.068400,NaN
1,Afghanistan,AFG,Control of Corruption - Governance estimate (a...,GOV_WGI_CC.EST,-1.63745,NaN,-1.543427,-1.545387,-1.507320,-1.571500,...,-1.565012,-1.543519,-1.539844,-1.501364,-1.400890,-1.222025,-1.171994,-1.198754,-1.308718,NaN
2,Afghanistan,AFG,Political Stability - Governance estimate (app...,GOV_WGI_PV.EST,-2.85050,NaN,-2.433571,-2.387388,-2.191258,-2.133959,...,-2.483493,-2.613931,-2.582405,-2.589371,-2.589690,-2.450639,-2.449249,-2.392283,-2.205211,NaN
3,Afghanistan,AFG,Population ages 65 and above (% of total popul...,SP.POP.65UP.TO.ZS,2.26197,2.261948,2.263974,2.266753,2.268647,2.269749,...,2.355497,2.359737,2.367120,2.376153,2.370734,2.352550,2.355142,2.377538,2.400970,2.425579
4,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,64.76728,64.597573,64.416888,64.176231,63.826609,63.319026,...,72.765910,65.862347,67.227177,58.330872,46.087094,NaN,NaN,NaN,NaN,NaN

In [16]:
df.describe()

,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
count,5013.000000,4105.000000,5254.000000,5243.000000,5312.000000,5526.000000,5529.000000,5730.000000,5760.000000,5848.000000,5846.000000,5858.000000,5855.000000,5819.000000,5401.000000,4752.000000,4133.000000,3398.000000,1058.000000
mean,49.243068,61.639680,48.948043,50.185489,51.266862,51.630343,52.747879,52.270219,52.709869,58.060691,58.637544,59.666102,60.139584,59.720376,64.779790,71.267367,73.917825,81.326160,38.002356
std,378.651904,425.043407,385.762711,411.382572,435.259703,451.496773,476.253462,492.561216,500.769491,610.186494,624.432633,645.954277,656.816409,647.405948,709.576737,761.341140,839.165082,940.419708,29.259682
min,-2.850500,0.000000,-2.506325,-2.576138,-2.842326,-2.607580,-2.668404,-3.051893,-3.012713,-2.640504,-2.730503,-2.724292,-2.617221,-2.656359,-2.667671,-2.612458,-2.626439,-2.750564,0.000000
25%,1.118950,6.122449,1.236050,1.183057,1.143204,1.401670,1.413106,1.454989,1.473781,1.599471,1.614053,1.650170,1.634560,1.600905,1.454745,1.336915,0.919060,0.477174,12.822250
50%,12.992000,26.000000,13.109175,12.978247,12.980167,14.423643,14.589602,13.006310,13.082967,13.603167,13.435204,13.875177,13.600000,14.032260,14.844730,16.113592,14.970060,11.585100,26.402924
75%,61.348675,69.428476,60.209790,60.124500,60.170996,58.907500,59.243000,57.904081,58.258750,61.195759,61.147000,61.228500,61.564331,61.631333,64.904000,69.473186,66.995000,65.116268,66.572500
max,15214.828000,15260.264000,15178.832900,15503.485800,15649.681300,15715.127100,16231.242800,17195.030300,17679.185600,22334.324200,22929.748600,23769.421400,24225.447300,23819.117300,25245.580500,25454.356700,26334.949400,26842.850100,128.558747

In [17]:
df[year_cols].isnull().sum()

2000 [YR2000]    1707
2001 [YR2001]    2615
2002 [YR2002]    1466
2003 [YR2003]    1477
2004 [YR2004]    1408
2005 [YR2005]    1194
2006 [YR2006]    1191
2007 [YR2007]     990
2008 [YR2008]     960
2016 [YR2016]     872
2017 [YR2017]     874
2018 [YR2018]     862
2019 [YR2019]     865
2020 [YR2020]     901
2021 [YR2021]    1319
2022 [YR2022]    1968
2023 [YR2023]    2587
2024 [YR2024]    3322
2025 [YR2025]    5662
dtype: int64